AWSTemplateFormatVersion: '2010-09-09'
Description: 'Minimal Gutenberg Infrastructure - Scrape, Parse, Format'

Resources:
  # S3 Bucket for content storage
  GutenbergBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'gutenberg-content-${AWS::AccountId}-${AWS::Region}'
      VersioningConfiguration:
        Status: Suspended
      LifecycleConfiguration:
        Rules:
          - Id: ArchiveOldContent
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: GLACIER
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # Secrets Manager for API keys
  GeminiAPISecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: 'gutenberg/gemini-api-key'
      Description: 'Gemini API key for text formatting'
      SecretString: !Sub |
        {
          "apiKey": "PLACEHOLDER_REPLACE_ME"
        }

  # Lambda execution role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: GutenbergPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt GutenbergBucket.Arn
                  - !Sub '${GutenbergBucket}/*'
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Ref GeminiAPISecret

  # Lambda function for scraping
  ScraperFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: GutenbergScraper
      Runtime: python3.10
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 900
      MemorySize: 512
      Environment:
        Variables:
          BUCKET_NAME: !Ref GutenbergBucket
          GEMINI_SECRET_ARN: !Ref GeminiAPISecret
      Code:
        ZipFile: |
          import json
          import boto3
          import requests
          import logging
          import os
          from datetime import datetime
          from urllib.parse import urlparse

          logger = logging.getLogger()
          logger.setLevel(logging.INFO)

          def lambda_handler(event, context):
              try:
                  book_id = event.get('bookId', 'unknown')
                  source_url = event.get('sourceUrl')
                  
                  if not source_url:
                      return {'statusCode': 400, 'error': 'sourceUrl is required'}
                  
                  logger.info(f"Scraping book {book_id} from {source_url}")
                  
                  # Download the book content
                  response = requests.get(source_url, timeout=30)
                  response.raise_for_status()
                  
                  # Get S3 client
                  s3 = boto3.client('s3')
                  bucket_name = os.environ['BUCKET_NAME']
                  
                  # Store raw content in S3
                  today = datetime.now().strftime('%Y-%m-%d')
                  s3_key = f"raw/{today}/{book_id}/book.txt"
                  
                  s3.put_object(
                      Bucket=bucket_name,
                      Key=s3_key,
                      Body=response.content,
                      ContentType='text/plain',
                      Metadata={
                          'source_url': source_url,
                          'scraped_at': datetime.now().isoformat()
                      }
                  )
                  
                  return {
                      'statusCode': 200,
                      'bookId': book_id,
                      'sourceUrl': source_url,
                      's3Key': s3_key,
                      'contentLength': len(response.content),
                      'scrapedAt': datetime.now().isoformat()
                  }
                  
              except Exception as e:
                  logger.error(f"Error scraping book: {str(e)}")
                  return {'statusCode': 500, 'error': str(e)}

Outputs:
  BucketName:
    Description: 'S3 bucket for storing books and processed content'
    Value: !Ref GutenbergBucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'

  ScraperFunctionArn:
    Description: 'Scraper Lambda function ARN'
    Value: !GetAtt ScraperFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ScraperFunctionArn'

  GeminiSecretArn:
    Description: 'Gemini API key secret ARN'
    Value: !Ref GeminiAPISecret
    Export:
      Name: !Sub '${AWS::StackName}-GeminiSecretArn'
